version: "3.8"

services:
  app:
    build: .
    image: videos-app-php:v1.2.2
    container_name: videos_container
    restart: unless-stopped
    env_file:
      - .env
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - vendor:/var/www/vendor
      - storage:/var/www/storage
    # depends_on:
      # - postgres
      # - redis
    # command: php artisan serve --host=0.0.0.0 --port=8000
    # ports:
      # - "8000:8000"
      # - "5173:5173"   # Vite

  nginx:
    image: nginx:1.25-alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - ./:/var/www:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  # postgres:
  #   image: postgres:16-alpine
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_DB: ${DB_DATABASE:-laravel}
  #     POSTGRES_USER: ${DB_USERNAME:-laravel}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pg_data:/var/lib/postgresql/data

  # redis:
  #   image: redis:7-alpine
  #   restart: unless-stopped
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data

volumes:
  # pg_data:
  # redis_data:
  vendor:
  storage:
